#!/bin/bash
SHELL=/bin/bash
PATH=/home/kayeholanda/.asdf/shims:/home/kayeholanda/.asdf/bin:/home/kayeholanda/.nvm/versions/node/v12.22.10/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
0 * * * * cd /home/kayeholanda/Documentos/testes/net-monit && ./monit.sh
